"""guardar correos pwneados en logs"""
import json
import os
import sys
import re
from intelxapi import intelx
from leakcheck import LeakCheckAPI_Public


def get_intelx_api_token():
    config_file = os.path.join('config', 'api_tokens.json')
    if os.path.exists(config_file):
        with open(config_file, 'r', encoding='utf-8') as f:
            config = json.load(f)
            return config.get('intelx', '')
    return ''

def search_records(target):
    api_key = get_intelx_api_token()
    ix = intelx(api_key)
    # Use the free IntelX API endpoint
    ix.API_ROOT = "https://free.intelx.io"
    # Define the buckets to search in
    search_buckets = ["leaks.public.wikileaks", "leaks.public.general", "dumpster", "documents.public.scihub"]
    # Search for records with the target email (prefiing with "@") and limit to 10 results
    print("[+] Searching for leaked email addresses...")
    results = ix.search(f"@{target}", maxresults=10, buckets=search_buckets)

    output_dir = os.path.join("logs", target, "dns")
    os.makedirs(output_dir, exist_ok=True)
    output_file = os.path.join(output_dir, "records.json")

    with open(output_file, 'w', encoding='utf-8') as f:
        json.dump(results, f, indent=4, ensure_ascii=False)

    print(f"[+] Records saved to {output_file}")

def search_emails(target):
    # Re-initialize the API with your API key
    api_key = get_intelx_api_token()
    ix = intelx(api_key)
    ix.API_ROOT = "https://free.intelx.io"

    # Load the records.json file generated by search_records
    records_file = os.path.join("logs", target, "dns", "records.json")
    if not os.path.exists(records_file):
        print("[-] records.json file not found.")
        return

    with open(records_file, 'r', encoding='utf-8') as f:
        data = json.load(f)

    records = data.get("records", [])
    found_emails = set()

    print("[+] Extracting email addresses from records...")

    for record in records:
        sid = record.get("storageid")
        bucket = record.get("bucket")
        ctype = record.get("type")
        mediatype = record.get("media", 24)

        if not sid or not bucket:
            continue

        try:
            # Retrieve file content using FILE_VIEW
            content = ix.FILE_VIEW(ctype=ctype, mediatype=mediatype, sid=sid, bucket=bucket)
            # Extract email addresses using a regular expression
            pattern = rf"[a-zA-Z0-9_.+-]+@{re.escape(target)}"
            emails = re.findall(pattern, content)
            for email in emails:
                found_emails.add(email)
        except Exception as e:
            print(f"[-] Error processing record {sid}: {e}")

    # Save the found email addresses to emails.txt
    output_file = os.path.join("logs", target, "dns", "emails.txt")
    with open(output_file, 'w', encoding='utf-8') as f:
        for email in found_emails:
            f.write(email + "\n")

    print(f"[+] Found {len(found_emails)} email addresses. Results saved to {output_file}")

def search_emails_leakcheck(target):
    public_api = LeakCheckAPI_Public()
    emails_file = os.path.join("logs", target, "dns", "emails.txt")
    if not os.path.exists(emails_file):
        print("[-] emails.txt file not found.")
        return
    with open(emails_file, 'r', encoding='utf-8') as f:
        emails = [line.strip() for line in f if line.strip()]
    for email in emails:
        try:
            result = public_api.lookup(query=email)
            print(f"[+] Result for {email}: {result}")
        except Exception as e:
            print(f"[-] Error for {email}: {e}")

def run_osint_mail(target):
    token = get_intelx_api_token()
    if not token:
        print("[-] IntelX API token not found, skipping functionality.")
        return
    search_records(target)
    search_emails(target)


if __name__ == "__main__":
    target = sys.argv[1]
    #run_osint_mail(target)
    search_emails_leakcheck(target)
