import json
import os
import sys
import re
from intelxapi import intelx


def get_intelx_api_token():
    config_file = os.path.join('config', 'api_tokens.json')
    if os.path.exists(config_file):
        with open(config_file, 'r', encoding='utf-8') as f:
            config = json.load(f)
            return config.get('intelx', '')
    return ''


def search_records(target):
    api_key = get_intelx_api_token()
    ix = intelx(api_key)
    # Use the free IntelX API endpoint
    ix.API_ROOT = "https://free.intelx.io"
    # Define the buckets to search in
    search_buckets = ["leaks.public.wikileaks", "leaks.public.general", "dumpster", "documents.public.scihub"]
    # Search for records with the target email (prefiing with "@") and limit to 10 results
    results = ix.search(f"@{target}", maxresults=10, buckets=search_buckets)

    output_dir = os.path.join("logs", target, "dns")
    os.makedirs(output_dir, exist_ok=True)
    output_file = os.path.join(output_dir, "records.json")

    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(results)
    print(f"Records saved to {output_file}")


def search_emails(target):
    # Re-initialize the API with your API key
    api_key = get_intelx_api_token()
    ix = intelx(api_key)
    ix.API_ROOT = "https://free.intelx.io"

    # Load the records.json file generated by search_records
    records_file = os.path.join("logs", target, "dns", "records.json")
    if not os.path.exists(records_file):
        print("[-] records.json file not found.")
        return

    with open(records_file, 'r', encoding='utf-8') as f:
        data = json.load(f)

    records = data.get("records", [])
    found_emails = set()

    for record in records:
        systemid = record.get("systemid")
        bucket = record.get("bucket")
        ctype = record.get("type") or record.get("ctype", 1)
        mediatype = record.get("media", 24)  # Default to text file

        if not systemid or not bucket:
            continue

        try:
            # Retrieve file content using FILE_VIEW
            content = ix.FILE_VIEW(ctype, mediatype, systemid, bucket=bucket)
            # Extract email addresses using a regular expression
            emails = re.findall(r"[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+", content)
            for email in emails:
                found_emails.add(email)
        except Exception as e:
            print(f"Error processing record {systemid}: {e}")

    # Save the found email addresses to emails.txt
    output_file = os.path.join("logs", target, "dns", "emails.txt")
    with open(output_file, 'w', encoding='utf-8') as f:
        for email in found_emails:
            f.write(email + "\n")

    print(f"Found {len(found_emails)} email addresses. Results saved to {output_file}")


if __name__ == "__main__":
    target = sys.argv[1]
    search_records(target)
    search_emails(target)
